### PR TITLE
9 - created user table

### LINKED ISSUE #9: Create Table for Users
## Instructions
- Using the DB model provided, write a `CREATE TABLE` statement in SQL for the Users table.
- Drop the table if it already exists.

## Notes
- For now, assume that all attributes should be `NOT NULL` unless otherwise specified.
- Arrows on the DB model indicate foreign key constraints

## Acceptance Criteria
- SQL creation code should exist in a file located in `server/schema/users.sql`

## Resources
[DB Model](https://www.figma.com/file/NDPdo1MR13qgsB4LubtzyZ/Database-Model?type=whiteboard&node-id=0-1&t=m1J0vcLI2mzIb5SN-0)
[Create Table Tutorial](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-create-table/)

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #9

### CODE REVIEW

**Review by michellelin1 — DISMISSED** [review]
LGTM! Good work! :)

**Review by michellelin1 — DISMISSED** [review]

**Comment by leeaj8-uci** [comment]
(Oh whoops: sorry I'll be playing around a little bit to try and figure out what's up with the GitHub actions: don't mind me)

**Review by leeaj8-uci — DISMISSED** [review]

**Review by leeaj8-uci — APPROVED** [review]
Sorry folks! I thought that fixing the GitHub actions would be a quick fix, but evidently not. Your code is still good to go as previously approved!

**Review by ThatMegamind — APPROVED** [review]
Looks good!

**Pull request merged**
